apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: metabase
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    audiences:
    - vault
    role: metabase
    serviceAccount: metabase-sa
    tokenExpirationSeconds: 600 