apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: metabase-db-credentials
  namespace: metabase
spec:
  type: kv-v2
  mount: metabase
  path: metabase
  destination:
    name: metabase_secrets
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth 