apiVersion: apps/v1
kind: Deployment
metadata:
  name: iceberg-rest-catalog
  namespace: kafka-platform
  labels:
    app: iceberg-rest-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iceberg-rest-catalog
  template:
    metadata:
      labels:
        app: iceberg-rest-catalog
    spec:
      containers:
      - name: iceberg-rest-catalog
        image: tabulario/iceberg-rest:1.5.0
        imagePullPolicy: IfNotPresent
        env:
        - name: CATALOG_WAREHOUSE
          value: "s3a://warehouse"
        - name: CATALOG_IO__IMPL
          value: "org.apache.iceberg.aws.s3.S3FileIO"
        - name: CATALOG_S3_ENDPOINT
          value: "http://minio.kyuubi.svc.cluster.local:9000"
        - name: CATALOG_S3_ACCESS__KEY__ID
          value: "minioadmin"
        - name: CATALOG_S3_SECRET__ACCESS__KEY
          value: "minioadmin123"
        - name: CATALOG_S3_PATH__STYLE__ACCESS
          value: "true"
        - name: REST_PORT
          value: "8181"
        ports:
        - containerPort: 8181
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /v1/config
            port: 8181
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /v1/config
            port: 8181
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: iceberg-rest-catalog
  namespace: kafka-platform
  labels:
    app: iceberg-rest-catalog
spec:
  selector:
    app: iceberg-rest-catalog
  ports:
  - port: 8181
    targetPort: 8181 