apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
  namespace: kafka-platform
  labels:
    app: kafka-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      initContainers:
      - name: wait-for-kafka
        image: busybox:1.35
        command: ['sh', '-c']
        args:
          - |
            echo "Waiting for Kafka to be ready..."
            until nc -z kafka 9092; do
              echo "Kafka not ready, waiting..."
              sleep 5
            done
            echo "Kafka is ready!"
      containers:
      - name: kafka-connect
        image: local-kafka-connect-full:latest
        imagePullPolicy: Never
        env:
        - name: CONNECT_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: CONNECT_GROUP_ID
          value: "kafka-connect-cluster"
        - name: CONNECT_CONFIG_STORAGE_TOPIC
          value: "kafka-connect-configs"
        - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: CONNECT_OFFSET_FLUSH_INTERVAL_MS
          value: "10000"
        - name: CONNECT_OFFSET_STORAGE_TOPIC
          value: "kafka-connect-offsets"
        - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: CONNECT_STATUS_STORAGE_TOPIC
          value: "kafka-connect-status"
        - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: CONNECT_KEY_CONVERTER
          value: "io.confluent.connect.avro.AvroConverter"
        - name: CONNECT_VALUE_CONVERTER
          value: "io.confluent.connect.avro.AvroConverter"
        - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL
          value: "http://schema-registry:8081"
        - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
          value: "http://schema-registry:8081"
        - name: CONNECT_INTERNAL_KEY_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_INTERNAL_VALUE_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_REST_ADVERTISED_HOST_NAME
          value: "kafka-connect"
        - name: CONNECT_REST_PORT
          value: "8083"
        - name: CONNECT_PLUGIN_PATH
          value: "/usr/share/confluent-hub-components"
        - name: CONNECT_LOG4J_ROOT_LOGLEVEL
          value: "INFO"
        ports:
        - containerPort: 8083
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        readinessProbe:
          httpGet:
            path: /connectors
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /connectors
            port: 8083
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
  namespace: kafka-platform
  labels:
    app: kafka-connect
spec:
  selector:
    app: kafka-connect
  ports:
  - port: 8083
    targetPort: 8083 