apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-connect-config
  namespace: kafka-platform
  labels:
    app: kafka-connect
data:
  log4j.properties: |
    log4j.rootLogger=INFO, stdout
    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=[%d] %p %m (%c)%n
    log4j.logger.org.apache.kafka.connect.runtime.rest=WARN
    log4j.logger.org.reflections=ERROR
  connect-log4j.properties: |
    log4j.rootLogger=INFO, stdout
    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=[%d] %p %m (%c:%L)%n
    log4j.logger.org.apache.kafka.connect.runtime.rest=WARN
    log4j.logger.org.reflections=ERROR 