apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- zookeeper.yaml
- kafka.yaml
- schema-registry.yaml
- kafka-connect.yaml
- kafka-connect-configmap.yaml
- akhq.yaml
- vault-auth.yaml
- vault-secret.yaml

labels:
  - pairs:
      app.kubernetes.io/name: kafka
      app.kubernetes.io/component: streaming
      app.kubernetes.io/part-of: data-platform 