apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: kafka-auth
  namespace: kafka-platform
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: kafka
    serviceAccount: default 