apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: kafka-config
  namespace: kafka-platform
spec:
  type: kv-v2
  mount: kafka
  path: config
  destination:
    name: kafka-config
    create: true
  vaultAuthRef: kafka-auth 