replicaCount: 1

image:
  repository: kyuubi-server
  tag: "1.10.0"

podAnnotations:
  karpenter.sh/do-not-disrupt: "true"

kyuubi:
  engine.share.level: SERVER
  session.engine.idle.timeout: PT15M
  engine.user.isolated.spark.session.idle.timeout: PT10M
  ha:
    enabled: true
    addresses: kyuubi-zk-zookeeper:2181
    namespace: kyuubi-dbt-shared

server:
  thriftBinary:
    enabled: true
  rest:
    enabled: true
  thriftHttp:
    enabled: true
  mysql:
    enabled: false

spark:
  kubernetes:
    container:
      image: spark-engine-iceberg:3.5.0-1.4.2
    authenticate:
      driver:
        serviceAccountName: kyuubi-sa
    scheduler:
      name: yunikorn
    driver:
      label:
        queue: root.dbt.internal
    executor:
      label:
        queue: root.dbt.internal
  executor:
    instances: 1
    memory: 12g
    cores: 2
  driver:
    memory: 5g
    memoryOverhead: 1g
  dynamicAllocation:
    enabled: true
    maxExecutors: 9
    minExecutors: 0
    executorIdleTimeout: 60s
    cachedExecutorIdleTimeout: 1800s
  eventLog:
    dir: /tmp/spark-events
  hive:
    metastore:
      uris: thrift://hive-metastore:9083
  sql:
    catalog:
      spark_catalog: org.apache.spark.sql.hudi.catalog.HoodieCatalog
  ui:
    prometheus:
      enabled: true

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - kyuubi-dbt
        topologyKey: kubernetes.io/hostname

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 500Mi

monitoring:
  prometheus:
    enabled: true
serviceMonitor:
  enabled: true 