apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mariadb-credentials
  namespace: kyuubi
spec:
  type: kv-v2
  mount: kyuubi
  path: kyuubi/database
  destination:
    name: mariadb-vault-secret
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth 