apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-sa
  namespace: grafana
  labels:
    app: grafana

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-role
  namespace: grafana
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-role-binding
  namespace: grafana
subjects:
- kind: ServiceAccount
  name: grafana-sa
  namespace: grafana
roleRef:
  kind: Role
  name: grafana-role
  apiGroup: rbac.authorization.k8s.io 