apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-admin-secret
  namespace: grafana
spec:
  type: kv-v2
  mount: grafana
  path: grafana
  destination:
    name: grafana-secret
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth 