apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: kyuubi
  labels:
    app: hive-metastore
    app.kubernetes.io/name: hive-metastore
    app.kubernetes.io/component: metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
      app.kubernetes.io/name: hive-metastore
      app.kubernetes.io/component: metastore
  template:
    metadata:
      labels:
        app: hive-metastore
        app.kubernetes.io/name: hive-metastore
        app.kubernetes.io/component: metastore
    spec:
      containers:
      - name: hive-metastore
        image: hive-metastore-custom:3.1.3
        imagePullPolicy: Never
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: hive-metastore-vault-secret
              key: mariadb_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hive-metastore-vault-secret
              key: mariadb_password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: hive-metastore-vault-secret
              key: mariadb_database
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: hive-metastore-vault-secret
              key: mariadb_host
        - name: MYSQL_PORT
          valueFrom:
            secretKeyRef:
              name: hive-metastore-vault-secret
              key: mariadb_port
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: hive-metastore-minio-secret
              key: access_key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: hive-metastore-minio-secret
              key: secret_key
        - name: MINIO_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: hive-metastore-minio-secret
              key: endpoint
        ports:
        - containerPort: 9083
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          tcpSocket:
            port: 9083
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 9083
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: kyuubi
spec:
  selector:
    app: hive-metastore
    app.kubernetes.io/name: hive-metastore
    app.kubernetes.io/component: metastore
  ports:
  - port: 9083
    targetPort: 9083
  type: ClusterIP 