apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: kyuubi
  labels:
    app: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
      - name: hive-metastore
        image: hive-metastore:3.1.3
        env:
        - name: MYSQL_USER
          value: "hive"
        - name: MYSQL_PASSWORD
          value: "hivepassword"
        - name: MYSQL_DATABASE
          value: "metastore"
        ports:
        - containerPort: 9083
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          tcpSocket:
            port: 9083
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 9083
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: kyuubi
spec:
  selector:
    app: hive-metastore
  ports:
  - port: 9083
    targetPort: 9083
  type: ClusterIP 