apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - hive-metastore-deployment.yaml
  - vault-secret.yaml

namespace: kyuubi

labels:
  - pairs:
      app.kubernetes.io/name: hive-metastore
      app.kubernetes.io/component: metastore 