apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: hive-metastore-credentials
  namespace: kyuubi
spec:
  type: kv-v2
  mount: kyuubi
  path: kyuubi/database
  destination:
    name: hive-metastore-vault-secret
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: hive-metastore-minio-credentials
  namespace: kyuubi
spec:
  type: kv-v2
  mount: kyuubi
  path: kyuubi/minio
  destination:
    name: hive-metastore-minio-secret
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth 