apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- vault-ingress.yaml
- kyuubi-ingress.yaml

namespace: ingress-nginx

patchesStrategicMerge:
- patches/ingress-config.yaml 