apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- vault-ingress.yaml
- kyuubi-ingress.yaml

namespace: ingress-nginx

patches:
- path: patches/ingress-config.yaml
  target:
    kind: Deployment
    name: ingress-nginx-controller 