apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: minio-credentials
  namespace: kyuubi
spec:
  type: kv-v2
  mount: kyuubi
  path: kyuubi/minio
  destination:
    name: minio-vault-secret
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth 