apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- source.yaml
- kustomizations.yaml

labels:
  - pairs:
      app.kubernetes.io/name: flux-system
      app.kubernetes.io/part-of: flux 