apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kyuubi-platform
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/anhhoangdev/LocalDataPlatform
  # secretRef:
  #   name: git-auth
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.jetstack.io 