apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/
- namespace.yaml

namespace: kafka-platform

labels:
  - pairs:
      app.kubernetes.io/name: kafka
      app.kubernetes.io/component: streaming
      app.kubernetes.io/part-of: data-platform 