apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-config-coordinator
  labels:
    app: trino
    role: coordinator

data:
  node.properties: |
    node.environment=production
    node.data-dir=/data/trino
  jvm.config: |
    -Xmx4G
    -XX:+ExitOnOutOfMemoryError
  config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=true
    http-server.http.port=8080
    query.max-memory=4GB
    query.max-memory-per-node=2GB
    discovery-server.enabled=true
    discovery.uri=http://trino:8080
    # Accept Presto (legacy) HTTP headers so Metabase Presto driver works
    protocol.v1.alternate-header-name=Presto
  log.properties: |
    io.trino=INFO
  iceberg.properties: |
    connector.name=iceberg
    hive.metastore.uri=thrift://hive-metastore.kyuubi.svc.cluster.local:9083
    hive.s3.aws-access-key=minioadmin
    hive.s3.aws-secret-key=minioadmin123
    hive.s3.endpoint=http://minio.kyuubi.svc.cluster.local:9000
    hive.s3.path-style-access=true
    hive.s3.ssl.enabled=false
