apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: trino-secret
  namespace: trino
spec:
  type: kv-v2
  mount: trino
  path: config
  destination:
    name: trino-secret
    create: true
  vaultAuthRef: trino-auth 