apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: trino-auth
  namespace: trino
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: trino
    serviceAccount: trino-sa 