apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/

namespace: kyuubi

labels:
  - pairs:
      app.kubernetes.io/name: mariadb
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: data-platform 