apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: keycloak-admin-secret
  namespace: keycloak
spec:
  type: kv-v2
  mount: kyuubi
  path: kyuubi/keycloak
  destination:
    name: keycloak-admin-secret
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth 