apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyuubi-dbt
  namespace: kyuubi
spec:
  interval: 5m
  chart:
    spec:
      chart: kyuubi
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: kyuubi-repo
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: kyuubi-dbt-values 