replicaCount: 3

image:
  repository: kyuubi-server
  tag: "1.10.0"

podAnnotations:
  karpenter.sh/do-not-disrupt: "true"

kyuubi:
  engine.share.level: USER
  session.engine.idle.timeout: PT30S
  # Iceberg Configuration - These will be passed to Spark engines as --conf parameters
  engine:
    sparkConf:
      spark.jars.packages: "org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.4.2"
      spark.sql.extensions: "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions"
      spark.sql.catalog.spark_catalog: "org.apache.iceberg.spark.SparkSessionCatalog"
      spark.sql.catalog.spark_catalog.type: "hive"
      spark.sql.catalog.spark_catalog.uri: "thrift://hive-metastore:9083"
      spark.sql.catalog.iceberg: "org.apache.iceberg.spark.SparkCatalog"
      spark.sql.catalog.iceberg.type: "hive"
      spark.sql.catalog.iceberg.uri: "thrift://hive-metastore:9083"
      spark.sql.catalog.shared: "org.apache.iceberg.spark.SparkCatalog"
      spark.sql.catalog.shared.type: "hive"
      spark.sql.catalog.shared.uri: "thrift://hive-metastore:9083"
  ha:
    enabled: true
    addresses: kyuubi-zk-zookeeper:2181
    namespace: kyuubi-dbt

server:
  thriftBinary:
    enabled: true
  rest:
    enabled: true
  thriftHttp:
    enabled: true
  mysql:
    enabled: false

spark:
  kubernetes:
    container:
      image: spark-engine-iceberg:3.5.0-1.4.2
    authenticate:
      driver:
        serviceAccountName: kyuubi-sa
    scheduler:
      name: yunikorn
    driver:
      label:
        queue: root.dbt.internal
    executor:
      label:
        queue: root.dbt.internal
  executor:
    memory: 4g
    cores: 2
  driver:
    memory: 2g
    memoryOverhead: 1g
  submit:
    deployMode: cluster
  eventLog:
    dir: /tmp/spark-events
  hive:
    metastore:
      uris: thrift://hive-metastore:9083
  sql:
    catalog:
      spark_catalog: org.apache.spark.sql.hudi.catalog.HoodieCatalog
  ui:
    prometheus:
      enabled: true

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - kyuubi-dbt
        topologyKey: kubernetes.io/hostname

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 500Mi

monitoring:
  prometheus:
    enabled: true
serviceMonitor:
  enabled: true 