apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyuubi-dbt-shared
  namespace: kyuubi
  labels:
    app: kyuubi-dbt-shared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyuubi-dbt-shared
  template:
    metadata:
      labels:
        app: kyuubi-dbt-shared
    spec:
      serviceAccountName: kyuubi-sa
      containers:
      - name: kyuubi-server
        image: kyuubi-server:1.10.0  # Essential: image.repository & tag
        imagePullPolicy: IfNotPresent
        ports:
        - name: thrift
          containerPort: 10009
        env:
        # All static configuration now lives in the mounted kyuubi-defaults.conf.
        
        # MinIO / S3 credentials
        - name: SPARK_HADOOP_FS_S3A_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: kyuubi-minio-secret
              key: access_key
        - name: SPARK_HADOOP_FS_S3A_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: kyuubi-minio-secret
              key: secret_key

        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        volumeMounts:
          - name: kyuubi-defaults
            mountPath: /opt/kyuubi/conf/kyuubi-defaults.conf
            subPath: kyuubi-defaults.conf
            readOnly: true
          - name: spark-driver-template
            mountPath: /opt/spark/pod-templates/driver-template.yaml
            subPath: driver-template.yaml
            readOnly: true
          - name: spark-executor-template
            mountPath: /opt/spark/pod-templates/executor-template.yaml
            subPath: executor-template.yaml
            readOnly: true
      volumes:
        - name: kyuubi-defaults
          configMap:
            name: kyuubi-dbt-shared-defaults
        - name: spark-driver-template
          configMap:
            name: spark-driver-template
            items:
              - key: driver-template.yaml
                path: driver-template.yaml
        - name: spark-executor-template
          configMap:
            name: spark-executor-template
            items:
              - key: executor-template.yaml
                path: executor-template.yaml 