apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyuubi-dbt
  namespace: kyuubi
  labels:
    app: kyuubi-dbt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyuubi-dbt
  template:
    metadata:
      labels:
        app: kyuubi-dbt
      annotations:
        karpenter.sh/do-not-disrupt: "true"
    spec:
      serviceAccountName: kyuubi-sa
      containers:
      - name: kyuubi-server
        image: kyuubi-server:1.10.0
        imagePullPolicy: Never
        ports:
        - containerPort: 10009
        - containerPort: 10099
        env:
        - name: SPARK_EXECUTOR_MEMORY
          valueFrom:
            secretKeyRef:
              name: kyuubi-spark-secret
              key: spark_executor_memory
        - name: SPARK_EXECUTOR_CORES
          valueFrom:
            secretKeyRef:
              name: kyuubi-spark-secret
              key: spark_executor_cores
        - name: SPARK_DRIVER_MEMORY
          valueFrom:
            secretKeyRef:
              name: kyuubi-spark-secret
              key: spark_driver_memory
        - name: SPARK_DRIVER_MEMORY_OVERHEAD
          value: "1g"

        # Database credentials
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: kyuubi-database-secret
              key: mariadb_host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: kyuubi-database-secret
              key: mariadb_port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: kyuubi-database-secret
              key: mariadb_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kyuubi-database-secret
              key: mariadb_password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: kyuubi-database-secret
              key: mariadb_database

        # MinIO / S3 credentials
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: kyuubi-minio-secret
              key: access_key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: kyuubi-minio-secret
              key: secret_key
        - name: SPARK_HADOOP_FS_S3A_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: kyuubi-minio-secret
              key: access_key
        - name: SPARK_HADOOP_FS_S3A_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: kyuubi-minio-secret
              key: secret_key
        - name: SPARK_HADOOP_FS_S3A_ENDPOINT
          value: "http://minio:9000"
        - name: SPARK_HADOOP_FS_S3A_PATH_STYLE_ACCESS
          value: "true"
        - name: SPARK_HADOOP_FS_S3A_IMPL
          value: "org.apache.hadoop.fs.s3a.S3AFileSystem"

        resources:
          requests:
            memory: "500Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        
        volumeMounts:
        - name: spark-driver-template
          mountPath: /opt/spark/pod-templates/driver-template.yaml
          subPath: driver-template.yaml
          readOnly: true
        - name: spark-executor-template
          mountPath: /opt/spark/pod-templates/executor-template.yaml
          subPath: executor-template.yaml
          readOnly: true
        - name: kyuubi-defaults
          mountPath: /opt/kyuubi/conf/kyuubi-defaults.conf
          subPath: kyuubi-defaults.conf
          readOnly: true
        
        livenessProbe:
          tcpSocket:
            port: 10009
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 10009
          initialDelaySeconds: 30
          periodSeconds: 10
      
      volumes:
      - name: spark-driver-template
        configMap:
          name: spark-driver-template
          items:
          - key: driver-template.yaml
            path: driver-template.yaml
      - name: spark-executor-template
        configMap:
          name: spark-executor-template
          items:
          - key: executor-template.yaml
            path: executor-template.yaml
      - name: kyuubi-defaults
        configMap:
          name: kyuubi-dbt-defaults

---
apiVersion: v1
kind: Service
metadata:
  name: kyuubi-dbt
  namespace: kyuubi
  labels:
    app: kyuubi-dbt
spec:
  type: ClusterIP
  ports:
  - name: thrift
    port: 10009
    targetPort: 10009
  - name: rest
    port: 10099
    targetPort: 10099
  selector:
    app: kyuubi-dbt 