apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyuubi-dbt-shared
  namespace: kyuubi
  labels:
    app: kyuubi-dbt-shared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyuubi-dbt-shared
  template:
    metadata:
      labels:
        app: kyuubi-dbt-shared
      annotations:
        karpenter.sh/do-not-disrupt: "true"
    spec:
      serviceAccountName: kyuubi-sa
      containers:
      - name: kyuubi-server
        image: kyuubi-server:1.10.0
        imagePullPolicy: Never
        ports:
        - containerPort: 10009
        - containerPort: 10099
        env:
        - name: KYUUBI_ENGINE_SHARE_LEVEL
          value: "SERVER"
        - name: KYUUBI_SESSION_ENGINE_IDLE_TIMEOUT
          value: "PT15M"
        - name: KYUUBI_ENGINE_USER_ISOLATED_SPARK_SESSION_IDLE_TIMEOUT
          value: "PT10M"
        - name: KYUUBI_HA_ENABLED
          value: "false"
        - name: SPARK_KUBERNETES_CONTAINER_IMAGE
          value: "spark-engine-iceberg:1.5.0"
        - name: SPARK_KUBERNETES_AUTHENTICATE_DRIVER_SERVICEACCOUNTNAME
          value: "kyuubi-sa"
        - name: SPARK_EXECUTOR_INSTANCES
          value: "1"
        - name: SPARK_EXECUTOR_MEMORY
          value: "12g"
        - name: SPARK_EXECUTOR_CORES
          value: "2"
        - name: SPARK_DRIVER_MEMORY
          value: "5g"
        - name: SPARK_DRIVER_MEMORY_OVERHEAD
          value: "1g"
        - name: SPARK_DYNAMICALLOCATION_ENABLED
          value: "true"
        - name: SPARK_DYNAMICALLOCATION_MAXEXECUTORS
          value: "9"
        - name: SPARK_DYNAMICALLOCATION_MINEXECUTORS
          value: "0"
        - name: SPARK_DYNAMICALLOCATION_EXECUTORIDLETIMEOUT
          value: "60s"
        - name: SPARK_DYNAMICALLOCATION_CACHEDEXECUTORIDLETIMEOUT
          value: "1800s"
        - name: SPARK_EVENTLOG_DIR
          value: "/tmp/spark-events"
        - name: SPARK_HIVE_METASTORE_URIS
          value: "thrift://hive-metastore:9083"
        resources:
          requests:
            memory: "500Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 10009
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 10009
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: kyuubi-dbt-shared
  namespace: kyuubi
spec:
  selector:
    app: kyuubi-dbt-shared
  ports:
  - name: thrift-binary
    port: 10009
    targetPort: 10009
  - name: rest-api
    port: 10099
    targetPort: 10099
  type: ClusterIP 