apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: kyuubi-database-secret
  namespace: kyuubi
spec:
  type: kv-v2
  mount: kyuubi
  path: kyuubi/database
  destination:
    name: kyuubi-database-secret
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: kyuubi-minio-secret
  namespace: kyuubi
spec:
  type: kv-v2
  mount: kyuubi
  path: kyuubi/minio
  destination:
    name: kyuubi-minio-secret
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: kyuubi-spark-secret
  namespace: kyuubi
spec:
  type: kv-v2
  mount: kyuubi
  path: kyuubi/spark
  destination:
    name: kyuubi-spark-secret
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth 