apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- rbac.yaml
- postgresql.yaml
- volumes.yaml
- airflow-webserver.yaml
- airflow-scheduler.yaml
- airflow-triggerer.yaml
- vault-secret.yaml
- vault-auth.yaml

labels:
- pairs:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/managed-by: kustomize

namespace: airflow 