apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-sa
  namespace: airflow
  labels:
    app: airflow

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-role
  namespace: airflow
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["create", "get", "list", "watch", "delete", "patch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-role-binding
  namespace: airflow
subjects:
- kind: ServiceAccount
  name: airflow-sa
  namespace: airflow
roleRef:
  kind: Role
  name: airflow-role
  apiGroup: rbac.authorization.k8s.io

---
# ClusterRole for cross-namespace access to kyuubi secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airflow-cross-namespace-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
  resourceNames: ["kyuubi-minio-secret"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow-cross-namespace-binding
subjects:
- kind: ServiceAccount
  name: airflow-sa
  namespace: airflow
roleRef:
  kind: ClusterRole
  name: airflow-cross-namespace-role
  apiGroup: rbac.authorization.k8s.io 