apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: airflow-secret
  namespace: airflow
spec:
  type: kv-v2
  mount: airflow
  path: airflow
  destination:
    name: airflow-secret
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth 