apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Infrastructure components
- flux-system/base
- ingress-nginx/overlays/minikube

# Application components
- hive-metastore
- kyuubi

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  environment: minikube 