apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Infrastructure components (base layer)
- flux-system/base
- ingress-nginx/overlays/minikube

# Shared Vault authentication
- vault-auth.yaml
- vault-secrets-operator-rbac.yaml

# Database and storage components (must be deployed first)
- mariadb
- minio

# Streaming platform (depends on storage)
- kafka

# Source database for CDC
- postgres-cdc

# Application components (depend on database and storage)
- hive-metastore
- kyuubi

# Monitoring / dashboards
- grafana

# Orchestration layer (depends on kyuubi for DBT service)
- airflow

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      environment: minikube 