apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/namespace.yaml
- base/rbac.yaml
- base/vault-secrets.yaml
- base/kyuubi-dbt-deployment.yaml
- base/kyuubi-dbt-shared-deployment.yaml

namespace: kyuubi 