apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.8.3"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 12h
  values:
    controller:
      # Use NodePort for minikube compatibility
      service:
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443
      
      # Resource limits for minikube
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
      
      # Enable metrics for monitoring
      metrics:
        enabled: false
        serviceMonitor:
          enabled: false
      
      # Disable admission webhooks for minikube
      admissionWebhooks:
        enabled: false
      
      # Configuration for minikube
      config:
        use-forwarded-headers: "true"
        compute-full-forwarded-for: "true"
      
      # Single replica for minikube
      replicaCount: 1
      
      # Node selector for minikube
      nodeSelector:
        kubernetes.io/os: linux
    
    # Default backend
    defaultBackend:
      enabled: true
      image:
        repository: registry.k8s.io/defaultbackend-amd64
        tag: "1.5"
      resources:
        requests:
          cpu: 10m
          memory: 20Mi
        limits:
          cpu: 20m
          memory: 30Mi 